export const citizenshipPrograms = [
  {
    id: "antigua-barbuda",
    country: "Antigua and Barbuda",
    slug: "antigua",
    overview:
      "In the heart of the Eastern Caribbean's Leeward Islands, Antigua and Barbuda gained independence from Britain in 1981. Known as 'the land of 365 beaches,' it's a favored tourist destination with main markets being the US, Canada, and Europe. Tourism makes up about 60% of their GDP, and the nation is home to a campus of the prestigious University of West Indies. The Citizenship-by-Investment Programme was introduced in 2013, providing a pathway for foreign investors and their families to obtain citizenship.",
    benefits: [
      "Enhanced global mobility opportunities for business and leisure travel",
      "Requires spending a minimum of five days in the country within the first five years",
      "No income tax, capital gains tax, inheritance tax, or tax on foreign income",
      "Dual citizenship allowed with no limitations",
      "Access to reduced tuition rates for universities in the United Kingdom",
      "Becoming a citizen does not automatically make one a tax resident",
      "Lifetime citizenship with no renewal requirements",
    ],
    processingTime: "Application timeframes vary",
    investment: {
      realEstate: "$300,000+",
      donation: "$230,000+ (National Development Fund)",
      universityFund: "$260,000+ (University of West Indies Fund)",
    },
    minInvestment: "$230,000",
    visaFree: "Global mobility opportunities",
    image: "/antigua-barbuda-flag-caribbean.jpg",
    brochureUrl: "https://drive.google.com/file/d/1fX73GAeEIxaDJIsB_8RfajSGjTRGJuSy/view?usp=sharing",
    summary:
      "A Caribbean paradise offering one of the region's most established citizenship programs since 2013, featuring minimal residency requirements (only 5 days in 5 years), comprehensive tax exemptions, and access to UK educational benefits.",
    eligibility: {
      primaryRequirements: [
        "Must be over 18 years old",
        "In good health with no serious medical conditions",
        "No criminal record carrying a custodial sentence of more than 6 months",
        "Must commit to at least five days of visitation within the first five years of citizenship",
      ],
      dependents: [
        "Spouse of the main applicant",
        "Children under 30 years old (must be financially dependent if over 18)",
        "Unmarried siblings of the investor or their spouse",
        "Parents and grandparents over 55 years of age who are financially dependent",
      ],
      restrictedNationalities: [
        "Afghanistan, Belarus, North Korea, Russia, Somalia, Sudan, Ukraine, and Yemen",
        "Exceptions for those who migrated before the age of majority or maintained permanent residency elsewhere for 10+ years",
        "Strict bar applies to Russian, Belarusian, and Ukrainian nationals (no exceptions)",
      ],
    },
  },
  {
    id: "saint-kitts-nevis",
    country: "St. Kitts and Nevis",
    slug: "stkitts",
    overview:
      "St. Kitts and Nevis, a former British colony that gained independence in 1983, offers the world's oldest Citizenship-by-Investment program, established in 1984. The majority of the nation's annual income of USD 1.5 billion comes from tourism, which draws more than 600,000 tourists each year. This 'Platinum Standard' program offers full citizenship in exchange for a significant financial investment in the country.",
    benefits: [
      "International mobility and global business opportunities",
      "No personal income tax, gift tax, inheritance tax, or net worth tax",
      "No minimum physical presence required",
      "Family inclusion: spouse, minor children, adult children up to 30, parents/grandparents over 65, and siblings under 30 (unmarried, financially dependent)",
      "Property investment hold time is 7 years",
      "Citizenship transferable to descendants for life",
      "Study with favourable conditions at some UK institutions, including free tuition at the University of the West Indies",
      "Dual citizenship permitted",
    ],
    processingTime: "Application timeframes vary",
    investment: {
      realEstate: "$400,000+",
      donation: "$250,000+",
      publicBenefit: "$250,000+",
    },
    minInvestment: "$250,000",
    visaFree: "Global mobility opportunities",
    image: "/saint-kitts-nevis-flag-caribbean.jpg",
    brochureUrl: "https://drive.google.com/file/d/1orlrH2csgkwXqbepP3ttghgtD8lMWQI3/view?usp=sharing",
    summary:
      "The world's oldest and most established CBI program since 1984, offering comprehensive tax benefits, extensive family inclusion options with citizenship transferable to future generations.",
  },
  {
    id: "dominica",
    country: "Dominica",
    slug: "dominica",
    overview:
      "Dominica is an island state in the Windward Islands, formerly a British colony. It is known for its unspoiled beauty, lush green forests, calm, and safety. English is the official language, though French is also widely spoken. Agriculture is the main driver of the economy. The Dominica Citizenship-by-Investment Programme allows the main applicant, their spouse, children, and parents to receive full citizenship in return for a significant financial investment in the country. Investors have been able to apply for citizenship in Dominica since 1993.",
    benefits: [
      "Enhanced international mobility for business and leisure purposes",
      "Competitive investment options in the Caribbean region",
      "No physical presence requirement",
      "Dual citizenship with no limitations",
      "Family inclusion: spouse, children under 30 (fully financially dependent), unmarried daughters under 25, parents over 65",
      "Property hold time for real estate option is 5 years",
      "Offers citizenship by marriage and descent",
    ],
    processingTime: "Application timeframes vary",
    investment: {
      realEstate: "$200,000+",
      donation: "$200,000+",
    },
    minInvestment: "$200,000",
    visaFree: "Global mobility opportunities",
    image: "/dominica-flag-caribbean.jpg",
    brochureUrl: "https://drive.google.com/file/d/1FhnW3JZID47rTlYNBJsLF4rDrRGF9vxs/view?usp=sharing",
    summary:
      "An established Caribbean citizenship program founded in 1993, known for its pristine natural beauty and straightforward application process with no residency requirements.",
  },
  {
    id: "grenada",
    country: "Grenada",
    slug: "grenada",
    overview:
      "One of the most beautiful islands in the West Indies, Grenada is known as the 'Island of Spice' for its diverse array of flavors including ginger, chocolate, nutmeg, cloves, and cinnamon. The flavors in this region are of the highest caliber and well-known worldwide. Citizenship can be obtained through the Grenada citizenship program, which has been in existence since 1997. Grenada is considered one of the safest and most stable countries in the Caribbean with a democratically elected government and low crime rate.",
    benefits: [
      "USA E-2 Investor Visa Treaty: Only Caribbean country with this E-2 visa pact with the US, enabling citizens to apply for a non-immigrant visa to reside and work there",
      "International business and lifestyle opportunities",
      "Family inclusion: spouse, children up to 30 years old (not required to be in school), siblings over 18 (unmarried, no children), parents over 55 who are fully dependent",
      "Transferable to descendants for life",
      "No residence requirement",
      "Dual citizenship with no limitations",
    ],
    processingTime: "Application timeframes vary",
    investment: {
      realEstate: "$270,000+",
      donation: "$235,000+",
    },
    minInvestment: "$235,000",
    visaFree: "Global mobility opportunities",
    image: "/grenada-flag-caribbean.jpg",
    brochureUrl: "https://drive.google.com/file/d/1qICRtFbITgNlx0tdqnGaWuRpwz1cvdIu/view?usp=sharing",
    summary:
      "The only Caribbean nation with US E-2 visa treaty access, offering citizenship in one of the safest Caribbean countries with extensive family inclusion options.",
  },
  {
    id: "saint-lucia",
    country: "St. Lucia",
    slug: "saint-lucia",
    overview:
      "St. Lucia is located in the eastern Caribbean Sea, south of Martinique and north-west of Barbados. An island made of volcanic lava primarily covered in rainforest is known for its twin peaks, the Pitons, and enchanted beaches. The island is well-known as a travel destination because of its stunning natural surroundings, including rainforests, national parks, botanical gardens, a world heritage site, beautiful Caribbean beaches, and even a drive-in volcano. Particularly in its worldwide banking and tourist industries, the island nation draws business and investment. St. Lucia's primary source of employment, foreign exchange profits, and revenue is tourism, which accounts for 65% of all jobs and income.",
    benefits: [
      "Global Mobility: Enhanced international travel opportunities for business and personal purposes",
      "International business access and opportunities",
      "No minimum physical presence requirement",
      "No taxes on income, wealth, or inheritance",
      "Short 5-year investment time for real estate or government bonds",
      "Offers citizenship by descent for future children",
      "Multiple investment pathways available",
    ],
    processingTime: "Application timeframes vary",
    investment: {
      realEstate: "$300,000+",
      bond: "$300,000+",
      donation: "$240,000+",
      enterprise: "$250,000+",
    },
    minInvestment: "$240,000",
    visaFree: "Global mobility opportunities",
    image: "/saint-lucia-flag-caribbean.jpg",
    brochureUrl: "https://drive.google.com/file/d/1XAG2B69lBXF0nb9bJzcL2D7qa-hrx_Sl/view?usp=sharing",
    summary:
      "A Caribbean gem famous for the Pitons volcanic peaks, offering diverse investment options including government bonds and enterprise projects, with attractive tax benefits.",
  },
  {
    id: "vanuatu",
    country: "Vanuatu",
    slug: "vanuatu",
    overview:
      "The Vanuatu Citizenship Development Support Program (DSP), introduced in 2017, is the only Citizenship-by-Investment program in the South Pacific and is described as the quickest way to obtain alternative citizenship through investment. Vanuatu is an island nation of 83 islands in the South Pacific, with close ties to Australia and New Zealand. Agriculture, tourism, offshore financial services, and the cattle industry are the four economic pillars of Vanuatu. For those looking to expand their worldwide mobility and pay less in taxes, Vanuatu citizenship is an appealing alternative.",
    benefits: [
      "Rapid Citizenship: Get your second passport in just 2-3 months",
      "Global Mobility: Visa-free or visa-on-arrival travel to over 117 countries, including the UK, Hong Kong, and Singapore",
      "Favorable Tax System: No wealth tax, gift tax, or income tax",
      "No Residency Requirement: No minimum presence requirements",
      "Family Inclusion: spouse, children under 25 (fully financially dependent), parents over 50",
      "Secrecy and Pre-approval: Process conducted in complete secrecy with pre-approval confirmation before full investment",
      "Minimum personal net assets of $250,000 USD required",
    ],
    processingTime: "2–3 months",
    investment: {
      donation: "$130,000+",
    },
    minInvestment: "$130,000",
    visaFree: "Global mobility opportunities",
    image: "/vanuatu-flag-pacific.jpg",
    brochureUrl: "https://drive.google.com/file/d/1DG3wQNOJo1o8-L_JQTGxaGpcDqkeH2Mb/view?usp=sharing",
    summary:
      "The fastest citizenship program in the world taking only 2-3 months, offering complete tax exemption and confidential processing for investors seeking rapid second citizenship in the South Pacific.",
  },
  {
    id: "turkey",
    country: "Turkey",
    slug: "turkiye",
    overview:
      "Turkey is a significant transcontinental nation that is strategically located and bordered by three seas. The position of this well-liked tourist destination makes it possible to connect with important markets via first-rate transportation systems. Istanbul, the largest city in Turkey, serves as the country's principal commercial and cultural hub despite the fact that Ankara is the country's capital. The program offers a simple application procedure without requiring the investor's personal presence or any disclosure of their assets or income earned in other nations.",
    benefits: [
      "Global Mobility: Visa-free travel to 110 countries, including Singapore, Hong Kong, Japan, Thailand, South Korea, Ukraine, Jordan, and Lebanon",
      "No Residency Required: No minimum residence requirements",
      "Dual Citizenship: Turkish law permits holding two citizenships",
      "Family Inclusion: Children up to 18 may be included",
      "Rapid Process: Passports typically issued within 4-5 months",
      "US Relocation Potential: Easier paths for Turkish nationals to relocate to the US under appropriate visa categories",
      "Lifetime Validity: Citizenship valid for life and transmitted to descendants",
      "Investment Benefits: Can earn rental income and resell property after 3 years",
    ],
    processingTime: "4–5 months",
    investment: {
      realEstate: "$400,000+",
      bankDeposit: "$500,000+",
      investmentFund: "$500,000+",
      capitalInvestment: "$500,000+",
      governmentBonds: "$500,000+",
      businessEmployment: "50 Turkish citizens",
    },
    minInvestment: "$400,000",
    visaFree: "Global mobility opportunities",
    image: "/turkey-flag.png",
    brochureUrl: "https://drive.google.com/file/d/1oceerSOkAckBIIaCJs3akM84wDMZv68k/view?usp=sharing",
    summary:
      "A transcontinental powerhouse connecting Europe and Asia, offering multiple flexible investment routes including real estate with rental income potential and pathways to US relocation for Turkish citizens.",
  },
  {
    id: "egypt",
    country: "Egypt",
    slug: "egypt",
    overview:
      "Egypt, a land steeped in ancient history and vibrant modern culture, is located in North Africa and boasts a strategic position bridging Africa and Asia via the Sinai Peninsula. Home to iconic monuments like the pyramids of Giza and the Sphinx, Egypt's history stretches back to one of the earliest civilizations. Beyond its historical wonders, Egypt is the most populous country in the Arab world and the third-largest in Africa, with a population concentrated along the fertile Nile River Valley. Successful applicants gain increased global mobility, access to the US E-2 Visa, and opportunities in Egypt's growing economy.",
    benefits: [
      "Fast Citizenship: About 6 months to process with no residency or language tests",
      "Family Passports: Includes spouse and children under 21 (spouse receives passport 2 years after investor)",
      "Tax Free Zones: Business tax exemptions in 9 zones",
      "US E-2 Visa: Pathway to live and work in the USA",
      "Visa-free or visa-on-arrival to over 80+ countries",
      "Real Estate Investment: Potential for profitable property investments",
      "Relaxed Regulation: No bank compliance check or source of investment verification",
    ],
    processingTime: "6 months",
    investment: {
      donation: "$250,000+",
      realEstate: "$300,000+",
      business: "$350,000+",
      bankDeposit: "$500,000+",
    },
    minInvestment: "$250,000",
    visaFree: "Global mobility opportunities",
    image: "/egypt-flag.jpg",
    brochureUrl: "https://drive.google.com/file/d/125IHAh3Cs-f3hGW9DX0W7e_O8l7Tc_Jx/view?usp=sharing",
    summary:
      "Ancient land of the pharaohs offering modern citizenship opportunities with US E-2 visa access, tax-free business zones, and relaxed investment verification requirements in the Arab world's most populous nation.",
  },
  {
    id: "nauru",
    country: "Nauru",
    slug: "nauru",
    overview:
      "Nauru is the world's smallest independent republic, located in the Central Pacific. With a rich history shaped by millennia of Micronesian and Polynesian cultures, this island nation offers a blend of cultural heritage and natural beauty that invites exploration beyond its size. Nauru has been inhabited for over 3,000 years, with its early settlers establishing a thriving community based on fishing, agriculture, and barter. Nauru's Citizenship-by-Investment Program, regulated by the Nauru Economic and Climate Resilience Citizenship Act 2024, offers a path to second citizenship for investors who contribute to the country's Treasury Fund to support climate resilience projects.",
    benefits: [
      "Global Mobility: Visa-free or visa-on-arrival access to 89 destinations including the UK, UAE, Singapore, Hong Kong, and Ireland (no EU access)",
      "No Residency Requirement: Applicants not required to reside in Nauru before or after obtaining passport",
      "Family Inclusion: Wide range including spouse/de facto partner, unmarried children up to 30, dependent parents 55+, and unmarried siblings of any age",
      "Multiple Citizenship: No restrictions on holding multiple citizenship",
      "Environmental Support: Investments support sustainability initiatives like renewable energy, water infrastructure, and community relocation to combat rising sea levels",
      "Fast Processing: Internal due diligence in 1 day, citizenship received within 4 weeks after payment",
    ],
    processingTime: "1–2 months (due diligence) + 4 weeks (after payment)",
    investment: {
      donation: "$105,000 (single), $110,000 (family up to 4), $115,000 (family 5+)",
    },
    minInvestment: "$105,000",
    visaFree: "Global mobility opportunities",
    image: "/nauru-flag-pacific.jpg",
    brochureUrl: "https://drive.google.com/file/d/1-rhsWSGQL9HdAJtQ9J9jZQi4L5nw2oPi/view?usp=sharing",
    summary:
      "The world's smallest republic offering the most affordable citizenship program focused on climate resilience, with exceptionally fast processing and flexible family inclusion including siblings of any age.",
  },
]
