export const residencyPrograms = [
  {
    id: "canada",
    country: "Canada",
    slug: "canada",
    summary:
      "Canada, a member of the G7, boasts a consistently robust economy that has outperformed many nations over the past decade. The country offers an attractive, cosmopolitan lifestyle well-suited to families. Its world-class cities are hubs of diversified business, lively social scenes, and rich cultural experiences.",
    description:
      "Canada's Start-up Visa offers high quality of life with free education for children and universal healthcare. Perfect for entrepreneurs seeking multicultural society with path to citizenship.",
    mobility: "Visa-free to 186 countries",
    investment: "CAD $350,000 minimum funding",
    processingTime: "12-18 months",
    family: "Spouse, children (any age)",
    path: "PR granted immediately, 730 days in 5 years to maintain, Citizenship after 3 years (1,095 days in 5 years)",
    image: "/placeholder.svg",
    flag: "🇨🇦",
    region: "North America",
    benefits: [
      "Global Mobility: Visa-free travel to 186 countries",
      "Thriving Lifestyle: High standard of living",
      "Universal Healthcare: Top-notch healthcare without upfront costs",
      "Abundant Resources: Rich in natural resources",
      "Education Excellence: Private schools and highly-ranked universities",
      "Natural Paradise: Stunning beauty, clean environment, exceptional safety",
      "Permanent residency granted immediately upon arrival",
      "PR not dependent on business success",
      "10% ownership in start-up with incubation training",
    ],
    eligibility: [
      "Minimum investment capital of CAD $350,000",
      "Acceptance from authorized designated organization",
      "Basic English or French proficiency (minimum CLB 5)",
      "Accredited investor status",
      "Meet Canadian admissibility requirements",
      "Two or more years post-secondary education (preferred)",
      "Prior business ownership or management experience (preferred)",
    ],
    brochureUrl: "https://drive.google.com/file/d/116fC2oLECZW3iZ6exXYFvvWCkTxlOn88/view?usp=sharing",
  },
  {
    id: "uae",
    country: "United Arab Emirates",
    slug: "uae",
    summary:
      "The UAE, located on the Arabian Peninsula, is a vibrant and modern nation known for its breathtaking architecture, booming business environment, and rich cultural heritage. It has become a global center for commerce, tourism, and innovation.",
    description:
      "UAE's Golden Visa offers tax-free income and world-class infrastructure with no stay requirements. Perfect for entrepreneurs and investors seeking a strategic business hub in the Middle East.",
    mobility: "Strategic location connecting major global markets",
    investment: "Property: AED 2M+ (10-year) | AED 750k+ (3-year)",
    processingTime: "2-3 months",
    family: "Spouse, children, parents eligible",
    path: "10-year Golden Visa (renewable) or 3-year Investor Visa, No citizenship path",
    image: "/placeholder.svg",
    flag: "🇦🇪",
    region: "Middle East",
    benefits: [
      "World-Class Infrastructure: State-of-the-art facilities and services",
      "Tax Benefits: Tax-free lifestyle with no income tax",
      "Strategic Location: Hub for international business and travel",
      "Cultural Diversity: Rich blend of cultures and traditions",
      "Safety and Security: Low crime rates, high standards of safety",
      "High Standard of Living: Access to luxurious amenities",
      "Professional Growth: Thriving job market and career opportunities",
    ],
    eligibility: [
      "Be at least 18 years old",
      "Purchase property, contribute to public investments, or establish business",
      "Satisfy UAE Investor Visa Programme requirements",
      "Possess valid travel documents",
    ],
    brochureUrl: "https://drive.google.com/file/d/1Forbz53yEBC9OT8kBSrEef7MXeAfGaGm/view?usp=sharing",
  },
  {
    id: "greece",
    country: "Greece",
    slug: "greece",
    summary:
      "Greece, frequently referred to as the home of Western civilization, is situated in southeast Europe. It is the home of democracy and one of Europe's oldest civilizations, rich in antiquities and historical monuments.",
    description:
      "Greece's Golden Visa provides EU residency with no stay requirements and affordable real estate options. Ideal for investors seeking Mediterranean lifestyle with EU citizenship path.",
    mobility: "Visa-free Schengen access to 27 countries",
    investment: "EUR 250,000 (most areas) | EUR 500,000 (Athens Central, Thessaloniki, Islands)",
    processingTime: "2-3 months",
    family: "Spouse, children up to 21, dependent parents",
    path: "Permanent residency from day one, 5-year renewable permit, Citizenship after 7 years",
    image: "/greece-golden-visa-residency.jpg",
    flag: "🇬🇷",
    region: "Europe",
    benefits: [
      "Permanent residency from day one",
      "Visa-free Schengen access",
      "Opportunity to live and do business in EU member states",
      "Full family residency for parents and children up to 21",
      "No minimum residency stay requirements",
      "Good standard of living and free access to Greek healthcare",
      "High calibre of education with access to prestigious universities",
      "8 weeks to become resident with renewable 5-year permit",
      "Possibility of owning shares and earning dividends",
    ],
    eligibility: [
      "Over 18 years old",
      "Spotless criminal record",
      "Medical insurance covering time in Greece",
      "National of non-EU/EEA country",
      "Regular salary or financial reference",
      "Personal and household health insurance",
      "Without serious medical conditions",
    ],
    brochureUrl: "https://drive.google.com/file/d/1OaPKEw5rbaycnTu-YFWa_Uywc7IniuNd/view?usp=sharing",
  },
  {
    id: "cyprus",
    country: "Cyprus",
    slug: "cyprus",
    summary:
      "Cyprus, an island in the Eastern Mediterranean, is renowned for its rich history, diverse culture, and scenic landscapes. Strategically located at the crossroads of Europe, Asia, and Africa, it serves as a hub for international business and travel.",
    description:
      "Cyprus offers EU residency with minimal stay requirements and 3-month processing time. Perfect for business professionals seeking Mediterranean lifestyle with EU benefits.",
    mobility: "Visa-free or visa on arrival to 177 countries, EU member since 2004",
    investment: "Real estate/Shares/Investment funds: EUR 300,000+",
    processingTime: "~3 months",
    family: "Spouse, dependent children up to 25",
    path: "Visit once every 2 years, Citizenship after 5 years of living in country",
    image: "/placeholder.svg",
    flag: "🇨🇾",
    region: "Europe",
    benefits: [
      "Fast and easy process, approximately 3 months",
      "Spouses and dependent children up to 25 included",
      "No physical residency required, only one visit every two years",
      "Entire process can be facilitated remotely (except biometric capturing)",
      "Eligible for Cyprus citizenship after 5 years",
      "Visa-free or visa on arrival to 177 countries",
      "Right to healthcare for all applicants",
      "No tax on worldwide income and no inheritance tax",
      "High standard of living with excellent healthcare and education",
      "Mediterranean climate with 300+ days of sunshine",
    ],
    eligibility: [
      "Main applicant at least 18 years old",
      "Clean criminal record and good reputation",
      "Good health with medical certificate",
      "Qualifying investment in one of the listed options",
      "Pass background check and due diligence review",
      "Secure annual income of at least EUR 50,000 from abroad",
      "Additional EUR 15,000 for spouse, EUR 10,000 per dependent child",
    ],
    brochureUrl: "https://drive.google.com/file/d/1aIIb1H0o6asDspxWfWQ2pvMnnwxh5BMQ/view?usp=sharing",
  },
  {
    id: "portugal",
    country: "Portugal",
    slug: "portugal",
    summary:
      "Portugal has a long history of worldwide exploration and trade and is one of Europe's most historically significant nations. Portugal now has visa-free access to all 26 European Schengen member states.",
    description:
      "Portugal's Golden Visa provides EU residency with minimal stay requirements and affordable cost of living. Ideal for investors seeking Mediterranean lifestyle with EU citizenship path.",
    mobility: "Visa-free to 27 Schengen countries",
    investment: "Property: EUR 500k+ | EUR 400k+ (low density) | EUR 350k+ (urban renewal) | Capital: EUR 250k-1.5M",
    processingTime: "1-4 months",
    family: "Spouse, children (any age), parents, grandparents",
    path: "7 days 1st year, 14 days every 2 years, Citizenship after 5 years with Portuguese language",
    image: "/portugal-golden-visa-residency.jpg",
    flag: "🇵🇹",
    region: "Europe",
    benefits: [
      "Permanent residency in Portugal",
      "Every family member eligible (spouse, parents, grandparents, unmarried children)",
      "High educational requirements with affordable tuition",
      "Top-notch international healthcare",
      "Minimal stay requirements (7 days/year average)",
      "Ability to live and work in Portugal with residency in another nation",
      "Citizenship after 5 years of residence",
      "Portugal allows dual citizenship",
    ],
    eligibility: [
      "Investment in qualifying property or capital transfer",
      "Meet minimum investment thresholds",
      "Basic understanding of Portuguese for citizenship",
      "Sincere ties to Portugal",
    ],
    brochureUrl: "https://drive.google.com/file/d/1gnN-WrtgUB44ckyfQd2VvW1Z1UEQ0WyM/view?usp=sharing",
  },
  {
    id: "malta",
    country: "Malta",
    slug: "malta",
    summary:
      "Malta is the largest of the three major islands that constitute the Maltese archipelago, located in the middle of the Mediterranean Sea directly south of Italy and north of Libya.",
    description:
      "Malta offers EU residency with English as an official language and favorable tax regime. Perfect for professionals and families seeking high quality of life in Europe.",
    mobility: "Visa-free travel within European Schengen Area",
    investment:
      "Option 1: EUR 68k contribution + EUR 300k/350k property | Option 2: EUR 98k contribution + EUR 10k/12k rent",
    processingTime: "6-8 months",
    family: "Spouse, children under 18, unmarried adults over 18, grandparents",
    path: "No minimum stay required, 5-year investment required, Work permit available",
    image: "/placeholder.svg",
    flag: "🇲🇹",
    region: "Europe",
    benefits: [
      "Visa-free travel within European Schengen Area",
      "No minimum days required to maintain resident status",
      "Streamlined application with 6-8 months processing",
      "English-speaking environment",
      "Dependents may be listed (spouse, children, grandparents)",
      "Little capital expenditure compared to other EU programs",
      "Right to live permanently in Malta",
      "Favorable tax system: only home income taxed for non-residents",
      "High educational standards with affordable tuition",
      "Simple work permit application for permanent residents",
      "Only first 5 years of investment necessary",
    ],
    eligibility: [
      "Principal applicant at least 18 years old",
      "Own at least EUR 500,000 in capital assets",
      "EUR 150,000 in readily accessible liquid assets",
      "Citizen of non-EU/EEA, Switzerland, Iceland, Liechtenstein, or Norway",
      "Consistent reliable means of income",
      "Hold legitimate travel papers",
      "Health insurance for self and dependents",
      "Fit and appropriate person evaluation",
      "English or Maltese communication skills",
      "Spend less than 183 days abroad",
      "EUR 2,000 charitable donation required",
    ],
    brochureUrl: "https://drive.google.com/file/d/1SjX0pnUKPzqXI5agyHsLKwOx7WFOOwxA/view?usp=sharing",
  },
  {
    id: "italy",
    country: "Italy",
    slug: "italy",
    summary:
      "Italy, known for its rich history and cultural heritage, is home to some of the world's most renowned art, architecture, and cuisine. The country boasts picturesque landscapes and vibrant cities filled with iconic landmarks.",
    description:
      "Italy's residency program offers access to 29 Schengen countries with flexible investment options. Fast processing in 1-2 months with world-class healthcare.",
    mobility: "Visa-free travel to 29 Schengen countries",
    investment: "Start-up: EUR 250k+ | Joint-stock company: EUR 500k+",
    processingTime: "1-2 months",
    family: "Full family residency extension",
    path: "2-year visa renewable for 3 years, PR after 5 years, Citizenship after 10 years tax residency",
    image: "/placeholder.svg",
    flag: "🇮🇹",
    region: "Europe",
    benefits: [
      "Fast approval in 30 days",
      "Investment required only after residency approval",
      "No language test or minimum stay requirement",
      "Extend residency to entire family",
      "Renewable every two years",
      "Visa-free travel to 29 Schengen countries",
      "Stay up to 3 months in any Schengen country within 6 months",
      "Eligible for permanent residency after 5 years",
      "Italian citizenship possible after 10 years tax residency",
      "Live, work, and study in Italy",
      "Access to world's highest-quality education and healthcare",
      "No taxes on gifts, inheritance, and profits made outside Italy",
    ],
    eligibility: [
      "Main applicant at least 18 years old",
      "Clean criminal record and good reputation",
      "Good health with medical certificate",
      "Make specified minimum investment within 3 months of entering Italy",
      "Maintain original investment for entire validity period",
    ],
    brochureUrl: "https://drive.google.com/file/d/1GRSfubOP8mGbsr503finea97flQrLft6/view?usp=sharing",
  },
  {
    id: "uk",
    country: "United Kingdom",
    slug: "uk",
    summary:
      "The UK is a well-integrated country and a coveted destination for private clients. London is the UK's cultural and business epicentre, magnetizing people from all corners of the world.",
    description:
      "UK's Innovator Founder Visa provides access to 185 countries with world-class education and strong financial opportunities. Ideal for entrepreneurs seeking global business hub access.",
    mobility: "Visa-free travel to UK and associated territories",
    investment: "£50,000+ invested in business to meet milestones",
    processingTime: "2-3 months",
    family: "Spouse, children under 18",
    path: "PR after 3 years if business goals met, Citizenship after 6 years",
    image: "/placeholder.svg",
    flag: "🇬🇧",
    region: "Europe",
    benefits: [
      "Permanent resident in 3 years if business goals met",
      "Visa-free travel in UK and associated territories",
      "London: leading global city in finance, trade, and culture",
      "Direct flights to almost any major city worldwide",
      "Very high quality education system",
      "Access to good healthcare benefits",
      "Strategic time zone for international business",
    ],
    eligibility: [
      "Over 18 years old",
      "Meet English language requirements",
      "Without criminal history",
      "Business assessed by endorsing body before applying",
      "At least £1,270 in bank account for 28 consecutive days",
      "Score 70 points total (50 for business, 20 for English/financial)",
      "Children under 18 and financially dependent",
    ],
    brochureUrl: "https://drive.google.com/file/d/1SROZ68MAursVT4ZzB84Ao_5LgO1FxRDM/view?usp=sharing",
  },
  {
    id: "hungary",
    country: "Hungary",
    slug: "hungary",
    summary:
      "Hungary is known for its diverse landscapes, ranging from the picturesque Danube River flowing through Budapest, to scenic wine-producing hills and the vast plains of the Great Hungarian Plain.",
    description:
      "Hungary's residency program provides access to the EU and Schengen area with fast 3-4 month processing. Ideal for families seeking European residency with path to citizenship.",
    mobility: "Visa-free to 27 EU/Schengen countries",
    investment: "Real estate fund: EUR 250k+ | Donation: EUR 1M+",
    processingTime: "3-4 months",
    family: "Spouse, children up to 26 (if single, studying, dependent), parents",
    path: "PR after 5 years, No stay required (visit recommended), Investments sold after 5 years",
    image: "/placeholder.svg",
    flag: "🇭🇺",
    region: "Europe",
    benefits: [
      "High standard of living with excellent healthcare and education",
      "Strategic location in Europe for business and travel",
      "Safe and secure environment with low crime rate",
      "Cultural richness and vibrant community life",
      "Spouse and children up to 26 qualify if criteria met",
      "Parents of both applicant and spouse can be included",
      "Entire family can reside in Hungary",
      "Access to free education",
      "Visa-free travel across EU countries including Schengen Area",
      "No physical stay required (visiting to prove ties recommended)",
      "Investments can be sold after 5 years",
    ],
    eligibility: [
      "Applicant at least 18 years old",
      "Clean criminal record and good reputation",
      "Good health with medical certificate",
      "Qualifying investment in legally defined options",
      "Sufficient funds in deposit account for investment and living expenses",
    ],
    brochureUrl: "https://drive.google.com/file/d/1TS66qlqmOKzmM1Edgm17GkhUitbp_MEr/view?usp=sharing",
  },
]
